name: CI

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    name: Build (${{ matrix.distro }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - distro: alpine
            dockerfile: docker/Dockerfile.alpine
            artifact_name: fh-linux-amd64-musl
          - distro: debian
            dockerfile: docker/Dockerfile.debian
            artifact_name: fh-linux-amd64-gnu

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image (${{ matrix.distro }})
        run: docker build -f ${{ matrix.dockerfile }} -t fh-${{ matrix.distro }} .

      - name: Run tests (${{ matrix.distro }})
        run: docker run --rm fh-${{ matrix.distro }} ./run_tests_release.sh

      - name: Extract Binary
        run: |
          id=$(docker create fh-${{ matrix.distro }})
          docker cp $id:/app/fh ${{ matrix.artifact_name }}
          docker rm -v $id

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_name }}

  build-macos:
    name: Build MacOS
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: amd64
            os: macos-15-intel
          - arch: arm64
            os: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: make -j4 TARGETS=release

      - name: Run Tests
        run: ./run_tests

      - name: Rename Binary
        run: mv fh fh-macos-${{ matrix.arch }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: fh-macos-${{ matrix.arch }}
          path: fh-macos-${{ matrix.arch }}

  release:
    name: Create Release
    needs: [build-and-test, build-macos]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: fh-*
          merge-multiple: true

      - name: List Artifacts
        run: ls -R

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: |
            fh-linux-amd64-musl
            fh-linux-amd64-gnu
            fh-macos-amd64
            fh-macos-arm64
